# Generated by Django 5.0.13 on 2025-11-12 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_phieu_bau', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('assistant', 'Assistant'), ('operator', 'Operator'), ('user', 'User')], default='user', max_length=16),
        ),
        migrations.CreateModel(
            name='PollMember',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_memberships', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_members', to=settings.AUTH_USER_MODEL)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='quan_ly_phieu_bau.poll')),
            ],
            options={
                'verbose_name': 'Thành viên cuộc bỏ phiếu',
                'verbose_name_plural': 'Thành viên cuộc bỏ phiếu',
                'unique_together': {('poll', 'account')},
            },
        ),
    ]
