# Generated by Django 5.0.13 on 2025-09-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_phieu_bau', '0002_ballot_is_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
