# Generated by Django 5.0.13 on 2025-11-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_phieu_bau', '0002_alter_account_role_pollmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='access_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
