# Generated by Django 5.0.13 on 2025-09-24 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_phieu_bau', '0003_alter_ballot_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballot',
            name='candidate',
        ),
        migrations.CreateModel(
            name='Ballot_Selection',
            fields=[
                ('selection_id', models.AutoField(primary_key=True, serialize=False)),
                ('ballot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quan_ly_phieu_bau.ballot')),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quan_ly_phieu_bau.candidate')),
            ],
        ),
    ]
