# Generated by Django 5.0.13 on 2025-11-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_phieu_bau', '0004_pollmember_approved_at_pollmember_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='require_approval',
            field=models.BooleanField(default=True),
        ),
    ]
