# Generated by Django 5.0.13 on 2025-11-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_phieu_bau', '0005_poll_require_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollmember',
            name='requested_role_change',
            field=models.CharField(blank=True, choices=[('assistant', 'Assistant'), ('operator', 'Operator')], max_length=16, null=True),
        ),
    ]
