# Generated by Django 5.0.13 on 2026-01-11 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poll', '0006_remove_voter_poll_voter_poll_id_3cdae2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tiêu đề thông báo', max_length=255)),
                ('message', models.TextField(help_text='Nội dung thông báo')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Dữ liệu bổ sung (member_id, ballot_id, etc.)')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Đã đọc chưa')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Thời gian tạo')),
                ('poll', models.ForeignKey(blank=True, help_text='Cuộc bỏ phiếu liên quan', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='poll.poll')),
                ('user', models.ForeignKey(help_text='Người nhận thông báo', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx')],
            },
        ),
    ]
