# Generated by Django 5.0.13 on 2026-01-11 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ballot', '0004_ballot_process_error_ballot_process_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('config_model', models.JSONField(default=dict, help_text='Cấu hình ô nào dùng model nào')),
                ('result_model', models.JSONField(default=dict, help_text='Kết quả detect của từng ô')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Thời gian xử lý (giây)', null=True)),
                ('status', models.CharField(choices=[('success', 'Thành công'), ('failed', 'Thất bại'), ('partial', 'Một phần thành công')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='ballot.ballot')),
            ],
            options={
                'verbose_name': 'Kết quả AI Model',
                'verbose_name_plural': 'Kết quả AI Models',
                'db_table': 'ai_model_result',
                'indexes': [models.Index(fields=['ballot'], name='ai_model_re_ballot__a5ca6d_idx'), models.Index(fields=['created_at'], name='ai_model_re_created_b1b44b_idx')],
            },
        ),
    ]
