# Generated by Django 5.0.13 on 2025-12-19 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poll', '0002_poll_hmac_secret_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_id', models.CharField(db_index=True, max_length=100)),
                ('result_model', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Thời gian xử lý (giây)', null=True)),
                ('status', models.CharField(choices=[('success', 'Thành công'), ('failed', 'Thất bại'), ('partial', 'Một phần thành công')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='poll.poll')),
            ],
            options={
                'verbose_name': 'Kết quả AI Model',
                'verbose_name_plural': 'Kết quả AI Models',
                'db_table': 'ai_model_result',
                'indexes': [models.Index(fields=['poll', 'model_id'], name='ai_model_re_poll_id_721d3e_idx'), models.Index(fields=['created_at'], name='ai_model_re_created_b1b44b_idx')],
            },
        ),
    ]
