# Generated by Django 5.0.13 on 2026-01-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0001_initial'),
        ('poll', '0006_remove_voter_poll_voter_poll_id_3cdae2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='aimodelresult',
            name='ai_model_re_poll_id_721d3e_idx',
        ),
        migrations.RemoveField(
            model_name='aimodelresult',
            name='model_id',
        ),
        migrations.AddIndex(
            model_name='aimodelresult',
            index=models.Index(fields=['poll'], name='ai_model_re_poll_id_be8d15_idx'),
        ),
    ]
