# Generated by Django 5.0.13 on 2026-01-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0002_remove_aimodelresult_ai_model_re_poll_id_721d3e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelresult',
            name='auto_check_enabled',
            field=models.BooleanField(default=False, help_text='Bật/tắt tự động kiểm phiếu'),
        ),
        migrations.AddField(
            model_name='aimodelresult',
            name='auto_check_max_ballots',
            field=models.IntegerField(blank=True, help_text='Số lượng phiếu tối đa cần kiểm (None = tất cả)', null=True),
        ),
        migrations.AddField(
            model_name='aimodelresult',
            name='auto_check_processed',
            field=models.IntegerField(default=0, help_text='Số phiếu đã kiểm tự động'),
        ),
    ]
