# Generated by Django 5.0.13 on 2025-12-05 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('poll_id', models.AutoField(primary_key=True, serialize=False)),
                ('access_code', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('counting_start_time', models.DateTimeField(null=True)),
                ('counting_end_time', models.DateTimeField(null=True)),
                ('total_ballots_issued', models.IntegerField(default=0)),
                ('total_ballots_received', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=32, null=True)),
                ('require_approval', models.BooleanField(default=True)),
                ('private_key', models.TextField(blank=True, null=True)),
                ('public_key', models.TextField(blank=True, null=True)),
                ('key_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('image_url', models.URLField(null=True)),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.poll')),
            ],
        ),
        migrations.CreateModel(
            name='PollMember',
            fields=[
                ('role', models.CharField(choices=[('manager', 'Trưởng ban'), ('operator', 'Tổ nhập liệu'), ('checkin', 'Tổ phát phiếu'), ('user', 'Người xem')], default='user', max_length=20)),
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('active', 'Đang hoạt động'), ('rejected', 'Từ chối'), ('banned', 'Bị chặn')], default='pending', max_length=16)),
                ('requested_role_change', models.CharField(blank=True, choices=[('manager', 'Trưởng ban'), ('operator', 'Tổ nhập liệu'), ('checkin', 'Tổ phát phiếu')], max_length=16, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_memberships', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_members', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_members', to=settings.AUTH_USER_MODEL)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='poll.poll')),
            ],
            options={
                'indexes': [models.Index(fields=['poll', 'account'], name='poll_pollme_poll_id_c0fc0f_idx')],
                'unique_together': {('poll', 'account')},
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('voter_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('code_id', models.CharField(max_length=128, null=True)),
                ('has_checked_in', models.BooleanField(default=False)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('poll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='poll.poll')),
            ],
            options={
                'indexes': [models.Index(fields=['poll', 'code_id'], name='poll_voter_poll_id_4b6f5d_idx')],
                'unique_together': {('poll', 'code_id'), ('poll', 'email')},
            },
        ),
    ]
