# Generated by Django 5.0.13 on 2025-12-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='hmac_secret_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
