# Generated by Django 5.0.13 on 2025-12-27 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_poll_hmac_secret_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['full_name'], name='poll_voter_full_na_5af753_idx'),
        ),
    ]
