# Generated by Django 5.0.13 on 2025-12-27 10:13

import security.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_voter_poll_voter_full_na_5af753_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='voter',
            name='poll_voter_poll_id_4b6f5d_idx',
        ),
        migrations.RemoveIndex(
            model_name='voter',
            name='poll_voter_full_na_5af753_idx',
        ),
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='voter',
            name='code_id_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='email_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='full_name_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='code_id',
            field=security.fields.EncryptedCharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='email',
            field=security.fields.EncryptedCharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='full_name',
            field=security.fields.EncryptedCharField(max_length=512, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together={('poll', 'code_id_hash'), ('poll', 'email_hash')},
        ),
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['poll', 'code_id_hash'], name='poll_voter_poll_id_3cdae2_idx'),
        ),
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['full_name_hash'], name='poll_voter_full_na_509274_idx'),
        ),
    ]
