# Generated by Django 5.0.13 on 2025-12-27 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_remove_voter_poll_voter_poll_id_4b6f5d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='voter',
            name='poll_voter_full_na_509274_idx',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='full_name_hash',
        ),
        migrations.AlterField(
            model_name='voter',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['full_name'], name='poll_voter_full_na_5af753_idx'),
        ),
    ]
