# Generated by Django 5.0.13 on 2025-12-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_remove_voter_poll_voter_full_na_509274_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='voter',
            name='poll_voter_poll_id_3cdae2_idx',
        ),
        migrations.RemoveIndex(
            model_name='voter',
            name='poll_voter_full_na_5af753_idx',
        ),
    ]
