# Generated by Django 5.0.13 on 2026-01-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_remove_voter_poll_voter_poll_id_3cdae2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='config_number',
            field=models.IntegerField(blank=True, choices=[(1, 'Cau hinh 1: VietNameOCR + YOLO-X'), (2, 'Cau hinh 2: Theo thu tu + YOLO-X')], help_text='Cau hinh AI model da su dung de kiem phieu', null=True),
        ),
    ]
