# Generated by Django 5.0.13 on 2026-01-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_poll_config_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_counting_started',
            field=models.BooleanField(default=False),
        ),
    ]
