# Generated by Django 5.0.13 on 2026-01-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_poll_is_counting_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='total_ballots_count',
            field=models.IntegerField(default=0),
        ),
    ]
