# Generated by Django 5.0.13 on 2026-01-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_poll_total_ballots_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_checking_started',
            field=models.BooleanField(default=False),
        ),
    ]
