# Generated by Django 5.0.13 on 2025-12-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
