# Generated by Django 5.0.13 on 2025-12-17 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BallotDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Document', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('margin_top', models.FloatField(default=2.0)),
                ('margin_bottom', models.FloatField(default=2.0)),
                ('margin_left', models.FloatField(default=2.0)),
                ('margin_right', models.FloatField(default=2.0)),
                ('font_family', models.CharField(default='Arial', max_length=50)),
                ('font_size', models.IntegerField(default=12)),
                ('header_content', models.JSONField(blank=True, default=dict)),
                ('title_content', models.JSONField(blank=True, default=dict)),
                ('body_content', models.JSONField(blank=True, default=list)),
                ('footer_content', models.JSONField(blank=True, default=list)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='ballot_pdfs/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
