# Generated by Django 5.0.13 on 2025-12-18 04:11

import django.db.models.deletion
import form.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
        ('poll', '0002_poll_hmac_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballotdocument',
            name='marker_distance_horizontal',
            field=models.FloatField(blank=True, help_text='Khoảng cách ngang giữa 2 biên lề (cm)', null=True),
        ),
        migrations.AddField(
            model_name='ballotdocument',
            name='marker_distance_vertical',
            field=models.FloatField(blank=True, help_text='Khoảng cách dọc giữa 2 biên lề (cm)', null=True),
        ),
        migrations.AddField(
            model_name='ballotdocument',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot_documents', to='poll.poll'),
        ),
        migrations.AlterField(
            model_name='ballotdocument',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=form.models.ballot_pdf_upload_path),
        ),
    ]
