"""
Django settings for kiem_phieu_bau project.

Generated by 'django-admin startproject' using Django 5.0.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""


from pathlib import Path
from dotenv import load_dotenv
import os

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'False') == 'True'
ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()] if os.getenv('ALLOWED_HOSTS') else []
CSRF_TRUSTED_ORIGINS = [h.strip() for h in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if h.strip()] if os.getenv('CSRF_TRUSTED_ORIGINS') else []

# Tắt APPEND_SLASH cho API (mobile app có thể gọi với hoặc không có trailing slash)
# APPEND_SLASH = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'account',  # Account models
    'poll',  # Poll, PollMember, Candidate, Voter models
    'ballot',  # Ballot, BallotSelection models
    'quan_ly_phieu_bau',
    'api',  # API cho mobile app
    'security',  # Cryptographic operations for QR code verification
    'form',  # Ballot form editor
    'preprocessing',  # Image preprocessing for AI
    'counting',  # AI model counting (TrOCR, YOLO)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'quan_ly_phieu_bau.middleware.LoginRequiredMessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'kiem_phieu_bau.request_logging_middleware.RequestLoggingMiddleware',  # Request logging
    'kiem_phieu_bau.rate_limiting_middleware.RateLimitMiddleware',  # Global rate limiting
    # 'kiem_phieu_bau.rate_limiting_middleware.UserBasedRateLimitMiddleware',  # User-based rate limiting (alternative)
]

ROOT_URLCONF = 'kiem_phieu_bau.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kiem_phieu_bau.wsgi.application'

# MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
        'ATOMIC_REQUESTS': True,
        'CONN_MAX_AGE': 0,
    },

    # 2. Kết nối dành riêng cho API cần Pooling
    'api_pool': {
        'ENGINE': os.getenv('DB_ENGINE'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        # Giữ kết nối sống 120 giây
        'CONN_MAX_AGE': 120,
        # Kiểm tra kết nối còn sống không trước khi dùng (Django 4.1+)
        # Rất quan trọng với MySQL để tránh lỗi "MySQL server has gone away"
        'CONN_HEALTH_CHECKS': True, 
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
        'ATOMIC_REQUESTS': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

import os

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_URL = os.getenv('STATIC_URL', 'static/')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
MEDIA_ROOT = os.path.join(BASE_DIR, os.getenv('MEDIA_ROOT', 'media'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Sử dụng Account làm user model mặc định
AUTH_USER_MODEL = 'account.Account'

# Đường dẫn login cho login_required
LOGIN_URL = '/account/login/'

STATIC_ROOT = os.path.join(BASE_DIR, os.getenv('STATIC_ROOT', 'staticfiles'))

# Logging Configuration - Show requests like runserver
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
            'datefmt': '%d/%b/%Y %H:%M:%S',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'api': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'quan_ly_phieu_bau': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

# ============================================
# RATE LIMITING CONFIGURATION
# ============================================

# Bật/tắt rate limiting
RATE_LIMIT_ENABLED = os.getenv('RATE_LIMIT_ENABLED', 'True') == 'True'

# Cấu hình rate limiting cho IP-based (Global)
RATE_LIMIT_REQUESTS = int(os.getenv('RATE_LIMIT_REQUESTS', '100'))  # Số requests tối đa
RATE_LIMIT_PERIOD = int(os.getenv('RATE_LIMIT_PERIOD', '60'))  # Thời gian (giây)

# Cấu hình rate limiting cho User-based
RATE_LIMIT_AUTHENTICATED_REQUESTS = int(os.getenv('RATE_LIMIT_AUTHENTICATED_REQUESTS', '200'))  # User đã đăng nhập
RATE_LIMIT_ANONYMOUS_REQUESTS = int(os.getenv('RATE_LIMIT_ANONYMOUS_REQUESTS', '50'))  # User chưa đăng nhập

# Whitelist IPs (không bị giới hạn)
RATE_LIMIT_WHITELIST_IPS = [
    '127.0.0.1',
    'localhost',
]

# Exempt paths (không bị giới hạn)
RATE_LIMIT_EXEMPT_PATHS = [
    '/static/',
    '/media/',
    '/admin/jsi18n/',  # Django admin javascript translations
]

# Cache backend cho rate limiting (sử dụng Django cache framework)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 10000,
        },
    },
    # Nếu muốn dùng Redis cho production (hiệu suất tốt hơn):
    # 'default': {
    #     'BACKEND': 'django.core.cache.backends.redis.RedisCache',
    #     'LOCATION': 'redis://127.0.0.1:6379/1',
    #     'OPTIONS': {
    #         'CLIENT_CLASS': 'django_redis.client.DefaultClient',
    #     },
    # },
}