"""
Django settings for kiem_phieu_bau project.

Generated by 'django-admin startproject' using Django 5.0.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""


from pathlib import Path
from dotenv import load_dotenv
import os

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'False') == 'True'
ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()] if os.getenv('ALLOWED_HOSTS') else []
CSRF_TRUSTED_ORIGINS = [h.strip() for h in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if h.strip()] if os.getenv('CSRF_TRUSTED_ORIGINS') else []

# Tắt APPEND_SLASH cho API (mobile app có thể gọi với hoặc không có trailing slash)
# APPEND_SLASH = False

# Application definition

INSTALLED_APPS = [
    'daphne',  # Django Channels ASGI server (phải đặt đầu tiên)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',  # Django Channels for WebSocket
    'account',  # Account models
    'poll',  # Poll, PollMember, Candidate, Voter models
    'ballot',  # Ballot, BallotSelection models
    'quan_ly_phieu_bau',
    'api',  # API cho mobile app
    'websocket',  # WebSocket notifications
    'security',  # Cryptographic operations for QR code verification
    'form',  # Ballot form editor
    'preprocessing',  # Image preprocessing for AI
    'counting',  # AI model counting (TrOCR, YOLO)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'quan_ly_phieu_bau.middleware.LoginRequiredMessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'kiem_phieu_bau.request_logging_middleware.RequestLoggingMiddleware',  # Request logging
    'kiem_phieu_bau.rate_limiting_middleware.RateLimitMiddleware',  # Global rate limiting
    # 'kiem_phieu_bau.rate_limiting_middleware.UserBasedRateLimitMiddleware',  # User-based rate limiting (alternative)
]

ROOT_URLCONF = 'kiem_phieu_bau.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kiem_phieu_bau.wsgi.application'

# Django Channels Configuration
ASGI_APPLICATION = 'kiem_phieu_bau.asgi.application'

# Channel layers (sử dụng Redis cho production hoặc InMemory cho development)
CHANNEL_LAYERS = {
    'default': {
        # Dùng Redis cho production (cần cài redis-server)
        # 'BACKEND': 'channels_redis.core.RedisChannelLayer',
        # 'CONFIG': {
        #     "hosts": [(os.getenv('REDIS_HOST', '127.0.0.1'), int(os.getenv('REDIS_PORT', 6379)))],
        #     "db": 3,  # ← Database 3 cho WebSocket
        # },
        
        # Dùng InMemoryChannelLayer cho development/testing (không cần Redis)
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
        'ATOMIC_REQUESTS': True,
        # Giảm CONN_MAX_AGE xuống 60s để giải phóng connection nhanh hơn
        'CONN_MAX_AGE': 60,
        'CONN_HEALTH_CHECKS': True,  # Kiểm tra kết nối còn sống không (tránh MySQL server has gone away)
    },

    # 2. Kết nối dành riêng cho API cần Pooling
    'api_pool': {
        'ENGINE': os.getenv('DB_ENGINE'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        # Giữ kết nối sống 120 giây
        'CONN_MAX_AGE': 120,
        # Kiểm tra kết nối còn sống không trước khi dùng (Django 4.1+)
        # Rất quan trọng với MySQL để tránh lỗi "MySQL server has gone away"
        'CONN_HEALTH_CHECKS': True, 
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
        'ATOMIC_REQUESTS': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

import os

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_URL = os.getenv('STATIC_URL', 'static/')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
MEDIA_ROOT = os.path.join(BASE_DIR, os.getenv('MEDIA_ROOT', 'media'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Sử dụng Account làm user model mặc định
AUTH_USER_MODEL = 'account.Account'

# Đường dẫn login cho login_required
LOGIN_URL = '/account/login/'

STATIC_ROOT = os.path.join(BASE_DIR, os.getenv('STATIC_ROOT', 'staticfiles'))

# Logging Configuration - Show requests like runserver
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
            'datefmt': '%d/%b/%Y %H:%M:%S',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'api': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'quan_ly_phieu_bau': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

# ============================================
# RATE LIMITING CONFIGURATION
# ============================================

# Bật/tắt rate limiting
RATE_LIMIT_ENABLED = os.getenv('RATE_LIMIT_ENABLED', 'True') == 'True'

# Cấu hình rate limiting cho IP-based (Global)
RATE_LIMIT_REQUESTS = int(os.getenv('RATE_LIMIT_REQUESTS', '100'))  # Số requests tối đa
RATE_LIMIT_PERIOD = int(os.getenv('RATE_LIMIT_PERIOD', '60'))  # Thời gian (giây)

# Cấu hình rate limiting cho User-based
RATE_LIMIT_AUTHENTICATED_REQUESTS = int(os.getenv('RATE_LIMIT_AUTHENTICATED_REQUESTS', '200'))  # User đã đăng nhập
RATE_LIMIT_ANONYMOUS_REQUESTS = int(os.getenv('RATE_LIMIT_ANONYMOUS_REQUESTS', '50'))  # User chưa đăng nhập

# Whitelist IPs (không bị giới hạn)
RATE_LIMIT_WHITELIST_IPS = [
    '127.0.0.1',
    'localhost',
]

# Exempt paths (không bị giới hạn)
RATE_LIMIT_EXEMPT_PATHS = [
    '/static/',
    '/media/',
    '/admin/jsi18n/',  # Django admin javascript translations
]

# Cache backend cho rate limiting (sử dụng Django cache framework)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 10000,
        },
    },
    # Nếu muốn dùng Redis cho production (hiệu suất tốt hơn):
    # 'default': {
    #     'BACKEND': 'django.core.cache.backends.redis.RedisCache',
    #     'LOCATION': 'redis://127.0.0.1:6379/2',
    #     'OPTIONS': {
    #         'CLIENT_CLASS': 'django_redis.client.DefaultClient',
    #     },
    # },
}


# =====================================================
# AI SERVER CONFIGURATION
# =====================================================

# Base URL của AI server (local: http://localhost:8080, docker: http://ai-server:8080)
AI_SERVER_BASE_URL = os.getenv('AI_SERVER_BASE_URL', 'http://localhost:8080').rstrip('/')

# Timeout mặc định khi gọi AI server
AI_SERVER_REQUEST_TIMEOUT = int(os.getenv('AI_SERVER_REQUEST_TIMEOUT', '300'))

# Timeout riêng cho health check (nên ngắn để UI phản hồi nhanh)
AI_SERVER_HEALTH_TIMEOUT = float(os.getenv('AI_SERVER_HEALTH_TIMEOUT', '0.5'))


# =====================================================
# CELERY CONFIGURATION (Async Task Queue)
# =====================================================

# Redis broker URL cho Celery (sử dụng để lưu trữ task queue - database 0)
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')

# Redis backend URL cho Celery (sử dụng để lưu trữ kết quả task - database 1)
# Tách riêng database để dễ quản lý, monitor và tối ưu hóa
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/1')

# Task serialization (định dạng dữ liệu khi truyền task)
CELERY_ACCEPT_CONTENT = ['json']  # Chỉ chấp nhận JSON format
CELERY_TASK_SERIALIZER = 'json'  # Serialize task thành JSON
CELERY_RESULT_SERIALIZER = 'json'  # Serialize kết quả thành JSON

# Timezone configuration
CELERY_TIMEZONE = 'Asia/Ho_Chi_Minh'  # Múi giờ Việt Nam
CELERY_ENABLE_UTC = False  # Không dùng UTC, dùng timezone trên

# Task settings (cấu hình task execution)
CELERY_TASK_TRACK_STARTED = True  # Theo dõi khi task bắt đầu
CELERY_TASK_TIME_LIMIT = 30 * 60  # Hard time limit: 30 phút (task sẽ bị kill nếu vượt quá)
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # Soft time limit: 25 phút (task sẽ nhận warning)

# Worker settings (cấu hình worker process)
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Worker chỉ lấy 1 task mỗi lần (phân phối công bằng)
CELERY_WORKER_MAX_TASKS_PER_CHILD = 20  # Worker tự restart sau 20 tasks (tránh memory leak khi xử lý ảnh lớn)
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 200000  # Restart worker nếu RAM > 200MB (tránh OOM)

# Result backend settings - TỰ ĐỘNG DỌN DẸP KẾT QUẢ CŨ (quan trọng khi xử lý hàng trăm phiếu)
CELERY_RESULT_EXPIRES = 3600  # Xóa kết quả sau 1 giờ (3600 giây) để tránh Redis bị đầy
CELERY_RESULT_BACKEND_ALWAYS_RETRY = True  # Retry khi lưu kết quả thất bại
CELERY_RESULT_BACKEND_MAX_RETRIES = 3  # Retry tối đa 3 lần

# Optional: Lưu kết quả task vào database thay vì Redis
# INSTALLED_APPS += ['django_celery_results']
# CELERY_RESULT_BACKEND = 'django-db'
# CELERY_CACHE_BACKEND = 'django-cache'