# Generated by Django 5.0.13 on 2025-12-18 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ballot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreprocessedBallot',
            fields=[
                ('preprocessing_id', models.AutoField(primary_key=True, serialize=False)),
                ('flattened_image', models.CharField(blank=True, max_length=512, null=True)),
                ('histogram_image', models.CharField(blank=True, max_length=512, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('cell_count', models.IntegerField(default=0)),
                ('ballot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preprocessed', to='ballot.ballot')),
            ],
            options={
                'verbose_name': 'Phiếu đã xử lý',
                'verbose_name_plural': 'Phiếu đã xử lý',
                'db_table': 'preprocessed_ballot',
            },
        ),
        migrations.CreateModel(
            name='BallotCell',
            fields=[
                ('cell_id', models.AutoField(primary_key=True, serialize=False)),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('cell_image', models.CharField(max_length=512)),
                ('preprocessed_ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='preprocessing.preprocessedballot')),
            ],
            options={
                'verbose_name': 'Ô phiếu',
                'verbose_name_plural': 'Ô phiếu',
                'db_table': 'ballot_cell',
                'unique_together': {('preprocessed_ballot', 'row', 'col')},
            },
        ),
    ]
