# Generated by Django 5.0.13 on 2025-12-28 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preprocessedballot',
            old_name='flattened_image',
            new_name='detection_image',
        ),
        migrations.RemoveField(
            model_name='preprocessedballot',
            name='histogram_image',
        ),
    ]
