# Generated by Django 5.0.13 on 2025-12-05 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('ballot_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=True)),
                ('ballot_image', models.ImageField(blank=True, null=True, upload_to='ballots/%Y/%m/%d/')),
                ('metadata', models.JSONField(null=True)),
                ('qr_signature', models.CharField(blank=True, max_length=1024, null=True)),
                ('qr_generated_at', models.DateTimeField(blank=True, null=True)),
                ('qr_payload', models.JSONField(blank=True, null=True)),
                ('input_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_ballots', to=settings.AUTH_USER_MODEL)),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.poll')),
            ],
        ),
        migrations.CreateModel(
            name='BallotSelection',
            fields=[
                ('selection_id', models.AutoField(primary_key=True, serialize=False)),
                ('ballot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ballot.ballot')),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.candidate')),
            ],
        ),
    ]
