# Generated by Django 5.0.13 on 2025-12-15 06:19

import ballot.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poll', '0002_poll_hmac_secret_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('ballot_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=True)),
                ('ballot_image', models.ImageField(blank=True, null=True, upload_to=ballot.models.ballot_image_upload_path)),
                ('metadata', models.JSONField(null=True)),
                ('qr_hmac', models.CharField(blank=True, max_length=64, null=True)),
                ('qr_generated_at', models.DateTimeField(blank=True, null=True)),
                ('qr_signature', models.CharField(blank=True, max_length=1024, null=True)),
                ('qr_payload', models.JSONField(blank=True, null=True)),
                ('input_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_ballots', to=settings.AUTH_USER_MODEL)),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.poll')),
            ],
        ),
        migrations.CreateModel(
            name='BallotSelection',
            fields=[
                ('selection_id', models.AutoField(primary_key=True, serialize=False)),
                ('ballot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ballot.ballot')),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='FormBallot',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('ballot_type', models.CharField(choices=[('mark_x', 'Đánh dấu X'), ('mark_v', 'Đánh dấu V'), ('cross_name', 'Gạch tên')], default='mark_x', max_length=20)),
                ('form_count', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=ballot.models.form_ballot_pdf_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='PHIẾU BẦU CỬ', max_length=255)),
                ('header_info', models.JSONField(blank=True, null=True)),
                ('footer_text', models.TextField(blank=True, null=True)),
                ('table_config', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_ballots', to='poll.poll')),
            ],
            options={
                'indexes': [models.Index(fields=['poll', 'ballot_type'], name='ballot_form_poll_id_bd9308_idx')],
            },
        ),
    ]
