# Generated by Django 5.0.13 on 2025-12-13 17:05

import ballot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='ballot_image',
            field=models.ImageField(blank=True, null=True, upload_to=ballot.models.ballot_image_upload_path),
        ),
    ]
