# Generated by Django 5.0.13 on 2025-12-27 10:43

import ballot.models
import security.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='ballot_image',
            field=security.fields.EncryptedImageField(blank=True, null=True, upload_to=ballot.models.ballot_image_upload_path),
        ),
    ]
