# Generated by Django 5.0.13 on 2025-12-14 14:05

import ballot.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0002_alter_ballot_ballot_image'),
        ('poll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormBallot',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('ballot_type', models.CharField(choices=[('mark_x', 'Đánh dấu X'), ('mark_v', 'Đánh dấu V'), ('cross_name', 'Gạch tên')], default='mark_x', max_length=20)),
                ('form_count', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=ballot.models.form_ballot_pdf_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_ballots', to='poll.poll')),
            ],
            options={
                'indexes': [models.Index(fields=['poll', 'ballot_type'], name='ballot_form_poll_id_bd9308_idx')],
            },
        ),
    ]
