# Generated by Django 5.0.13 on 2026-01-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0002_alter_ballot_ballot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='is_post_checked',
            field=models.BooleanField(default=False),
        ),
    ]
