# Generated by Django 5.0.13 on 2026-01-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0003_ballot_is_post_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='process_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ballot',
            name='process_status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('failed', 'Lỗi')], default='pending', max_length=20),
        ),
    ]
