# Generated by Django 5.0.13 on 2025-12-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0003_formballot'),
    ]

    operations = [
        migrations.AddField(
            model_name='formballot',
            name='footer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formballot',
            name='header_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formballot',
            name='table_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formballot',
            name='title',
            field=models.CharField(default='PHIẾU BẦU CỬ', max_length=255),
        ),
    ]
