# Generated by Django 5.0.13 on 2025-12-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0004_formballot_footer_text_formballot_header_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='qr_hmac',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
