# Generated by Django 5.0.13 on 2026-01-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0004_ballot_process_error_ballot_process_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='counting_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ballot',
            name='counting_status',
            field=models.CharField(choices=[('pending', 'Chờ kiểm'), ('processing', 'Đang kiểm'), ('completed', 'Đã kiểm'), ('failed', 'Lỗi kiểm')], default='pending', max_length=20),
        ),
    ]
