# Generated by Django 5.0.13 on 2026-01-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0005_add_counting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
