# Generated by Django 5.0.13 on 2026-01-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0006_ballot_is_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballot',
            name='is_uploaded',
        ),
    ]
