# Generated by Django 5.0.13 on 2026-01-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0007_remove_ballot_is_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='process_status',
            field=models.CharField(choices=[('no_upload', 'chưa tải lên'), ('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('failed', 'Lỗi')], default='no_upload', max_length=20),
        ),
    ]
