# Generated by Django 5.0.13 on 2026-01-21 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0008_alter_ballot_process_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='checking_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ballot',
            name='checking_locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checking_locked_ballots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ballot',
            name='checking_status',
            field=models.CharField(choices=[('NEW', 'Mới - Chưa ai làm'), ('PROCESSING', 'Đang xử lý - Đang bị khóa bởi User'), ('DONE', 'Hoàn thành')], default='NEW', max_length=20),
        ),
    ]
