# Generated by Django 5.0.13 on 2026-01-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0009_ballot_checking_locked_at_ballot_checking_locked_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballot',
            name='is_checked',
        ),
        migrations.RemoveField(
            model_name='ballot',
            name='is_post_checked',
        ),
    ]
