# Generated by Codex on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0010_remove_ballot_is_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='checking_status',
            field=models.CharField(
                choices=[
                    ('NEW', 'Mới - Chưa ai làm'),
                    ('PROCESSING', 'Đang xử lý - Đang bị khóa bởi User'),
                    ('DONE', 'Hoàn thành'),
                    ('SKIP', 'Bỏ qua phiếu này'),
                ],
                default='NEW',
                max_length=20,
            ),
        ),
    ]
